name: Build - Test -- Server

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./server/GestaoDeEstacionamento.sln --configuration Release
  
  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
    
      - name: Run tests
        run: dotnet test ./server/GestaoDeEstacionamento.sln --configuration Release --verbosity normal
        env: 
          ASPNET_ENVIRONMENT: "GITHUB_ACTIONS"
          SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
          NEWRELIC_LICENSE_KEY: ${{ secrets.NEWRELIC_LICENSE_KEY }}